export default {
    TITLE_LOGIN_SUCCESSFUL: "Inicio de sesión exitoso",
    MSG_LOGIN_SUCCESSFUL: "Ha iniciado sesión correctamente.",
    TITLE_LOGIN_FAILED: "Inicio de sesión fallido",
    MSG_LOGIN_FAILED: "Correo electrónico o contraseña no válidos. Vuelva a intentarlo.",
    TITLE_REGISTER_SUCCESSFUL: "Registro exitoso",
    MSG_REGISTER_SUCCESSFUL: "Usuario registrado correctamente.",
    TITLE_REGISTER_FAILED: "Registro fallido",
    MSG_REGISTER_FAILED: "Se ha producido un error durante el registro. Por favor, inténtelo de nuevo.",
    TITLE_LOGGED: "Sesión cerrada",
    MSG_LOGGED: "Ha cerrado la sesión correctamente.",
    TITLE_OPERATION_SUCCESSFUL: "Operación exitosa",
    TITLE_OPERATION_FAILED: "Error",
    MSG_OPERATION_FAILED: "Error al realizar la operación. Por favor, inténtelo de nuevo.",
    MSG_SAVE_CARD_SUCCESSFUL: "Información registrada exitosamente.",
    MSG_UPDATE_CARD_SUCCESSFUL: "Información actualizada exitosamente.",
}
